### ISSUE TITLE
There are no functions in the module Nodes

### ISSUE THREAD

**Issue by aleksandrvolk** [Danedeath/prox-guac-client#2]
Uncaught Error: Call to undefined method Proxmox\Nodes::qemuDelete()
Uncaught Error: Call to undefined method Proxmox\Nodes::qemuAgentNetwork()
Uncaught Error: Call to undefined method Proxmox\Nodes::qemuOsInfo()

**Comment by Danedeath** [comment]
Adding the modified versions to the repo; apologies

**Comment by Danedeath** [comment]
Pushed an updated version of classes.php that resolves the issue. Thank you!
